language: php

sudo: false

dist: trusty

git:
  depth: 5

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls
